# Task A

In [1]:
def normalize(x):
    """
    Normalizes the matrix x (n rows of samples, d columns of dimensions)
    """
    return (x - x.mean(0))/x.std(0)

In [2]:
import numpy as np

In [3]:
x = np.array([[1,0,1],
            [0.5,1,0],
            [1,0,1]])

# Task B

In [4]:
def euclidian_distance(A, B):
    return np.sqrt(((A - B)*(A - B)).sum())

In [5]:
euclidian_distance(np.ones((2)), np.zeros((2)))

1.4142135623730951

In [6]:
def pairwize_distances(P, Q):
    D = np.zeros((len(P), len(Q)))
    for i in range(len(P)):
        for j in range(len(Q)):
            D[i, j] = euclidian_distance(P[i], Q[j])
    return D

In [7]:
P = np.ones((5,2))*2
Q = np.zeros((5,2))

In [8]:
pairwize_distances(P, Q)

array([[2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712],
       [2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712],
       [2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712],
       [2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712],
       [2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712]])

# Task C

Input : (Xn) : n d-dimentional vectors <br/>
Theta1, theta2

In [9]:
np.linalg.inv(np.eye(2))

array([[1., 0.],
       [0., 1.]])

In [21]:
def likelihood(X, theta1, theta2):
    """
    X (n * d)
    theta (mu, sigma)
    """
    det1, det2 = np.linalg.det(theta1[1]), np.linalg.det(theta2[1]) #determinant
    if (det1 == 0 or det2 == 0):
        print("Matrix non inversible")
        return 
    inv1, inv2 = np.linalg.inv(theta1[1]), np.linalg.inv(theta2[1]) #inverse
    d = X.shape[1]
    p1 = np.diag(1/(np.pi**(d/2) * np.sqrt(np.abs(det1)))* np.exp(-0.5 * (X - theta1[0]).reshape((-1, d))@inv1@(X - theta1[0]).reshape((d, -1))))
    p2 = np.diag(1/(np.pi**(d/2) * np.sqrt(np.abs(det2)))* np.exp(-0.5 * (X - theta2[0]).reshape((-1, d))@inv1@(X - theta2[0]).reshape((d, -1))))
    return 1 * (p1 > p2) + 2 * (p2 > p1)

In [11]:
X = np.random.randint(10, size = (100,4))

In [12]:
mu1, mu2 = np.random.randint(10, size = (1,4)), np.random.randint(10, size = (1,4))

In [13]:
sigma1, sigma2 = np.random.randint(10, size = (4,4)), np.random.randint(10, size = (4,4))

In [22]:
likelihood(X, [mu1, sigma1], [mu2, sigma2])

(100,)


array([1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1,
       1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1])

In [15]:
d = 4

In [16]:
(X - mu).reshape((-1, d))

NameError: name 'mu' is not defined